-- =====================================================================
-- V1: esquema completo de Rate My Prof.
--
-- Refleja lo que Hibernate venía generando con ddl-auto=update; a partir
-- de esta migración el dueño del esquema es Flyway y Hibernate solo
-- valida (ddl-auto=validate). Cualquier cambio de esquema nuevo va en
-- una migración V3, V4, ... — no se edita esta.
-- =====================================================================

CREATE TABLE materias (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    -- Año de cursada según el plan (1..5). Nullable: ver Materia.java.
    anio   INTEGER
);

CREATE TABLE profesores (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Vacío cuando no se conoce (los horarios solo publican apellidos).
    nombre   VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL
);

CREATE TABLE catedras (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id BIGINT NOT NULL REFERENCES profesores (id),
    materia_id  BIGINT NOT NULL REFERENCES materias (id),
    -- Una cátedra ES el par profesor+materia: no puede repetirse.
    UNIQUE (profesor_id, materia_id)
);

CREATE TABLE usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(255) NOT NULL,
    -- El DNI es la identidad: con él se loguea (no hay contraseña).
    dni            VARCHAR(255) NOT NULL UNIQUE,
    -- Opcional; único solo si está presente.
    email          VARCHAR(255) UNIQUE,
    fecha_registro TIMESTAMP(6),
    rol            VARCHAR(255) NOT NULL DEFAULT 'USER'
                   CHECK (rol IN ('USER', 'ADMIN'))
);

CREATE TABLE reviews (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT NOT NULL REFERENCES usuarios (id),
    catedra_id     BIGINT NOT NULL REFERENCES catedras (id),
    puntuacion     INTEGER NOT NULL CHECK (puntuacion BETWEEN 1 AND 5),
    comentario     TEXT NOT NULL,
    -- "1C 2025" / "2C 2025" (ver Cuatrimestre.java). Nullable: las reviews
    -- anteriores al campo no lo tienen; se endurecerá cuando se backfilleen.
    cuatrimestre   VARCHAR(7),
    fecha_creacion TIMESTAMP(6)
);

CREATE TABLE votos_util (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT NOT NULL REFERENCES usuarios (id),
    review_id      BIGINT NOT NULL REFERENCES reviews (id),
    fecha_creacion TIMESTAMP(6),
    -- Un usuario no puede votar dos veces la misma review.
    UNIQUE (usuario_id, review_id)
);

-- Índices para las FKs que se recorren al listar (el UNIQUE de catedras ya
-- cubre las búsquedas por profesor_id como prefijo).
CREATE INDEX idx_catedras_materia ON catedras (materia_id);
CREATE INDEX idx_reviews_catedra ON reviews (catedra_id);
CREATE INDEX idx_reviews_usuario ON reviews (usuario_id);
CREATE INDEX idx_votos_util_review ON votos_util (review_id);
